### PR TITLE
Update for Orleans 8.2

### PR DESCRIPTION
**Pull request by oising**
Update OrleansTestKit to work with [Orleans 8.2](https://github.com/dotnet/orleans/releases/tag/v8.2.0)

- [x] update Orleans nugets
- [x] add missing methods on modified interfaces
- [x] add testkit wiring for new RegisterGrainTimer
  - [x] support cancellation token in callback 

closes https://github.com/OrleansContrib/OrleansTestKit/issues/164

### CODE REVIEW

**Comment by jkonecki** [comment]
Hi @oising , are you working on RegisterGrainTimer? If so, do you have any ETA? Would you like some help?

**Comment by oising** [comment]
> Hi @oising , are you working on RegisterGrainTimer? If so, do you have any ETA? Would you like some help?

Yeah, that's the one. I think I'm okay? It will basically work the same as the legacy timer. The grain timer is meant to respect interleaving rules but I don't believe testkit does in general, so I don't have much to do to implement.

**Comment by seniorquico** [comment]
> The grain timer is meant to respect interleaving rules but I don't believe testkit does in general

That's correct, the TestKit does not implement any special threading controls. It's up to the unit test implementer to ensure the grain instance is correctly called in a single-threaded fashion. (And anyone looking for managed single-threaded execution should turn to the Orleans TestCluster.)

**Comment by oising** [comment]
@jkonecki @seniorquico I'll have the PR ready for review for end of day today.

**Comment by oising** [comment]
Ready for first review.

**Comment by jkonecki** [comment]
Looks good to me, thank you! Leaving to @seniorquico to review and approve.

File: test/OrleansTestKit.Tests/Tests/TimerTests.cs [hunk 1]
```diff
@@ -1,11 +1,59 @@
...
+        // Act
+        await Silo.FireTimerAsync(HelloTimers.GrainTimer0);
+
+        // Assert
+        var state = Silo.State<HelloTimers, HelloTimersState>();
+        state.GrainTimer0Fired.Should().BeTrue();
+    }
+
+    [Fact]
+    public async Task ShouldFirstGrainTimerAsync()
```
Comment (seniorquico) [inline test/OrleansTestKit.Tests/Tests/TimerTests.cs:25]: Is this an improved version of `ShouldFireFirstGrainTimerAsync` above? Do we want both?

Comment (oising) [reply test/OrleansTestKit.Tests/Tests/TimerTests.cs:25]: Not sure... this only tests the new RegisterGrainTimer timer, and the other tests the legacy timer. If you want them separate, we keep it.

Comment (oising) [reply test/OrleansTestKit.Tests/Tests/TimerTests.cs:25]: Oh, ther's a dupe -- I didn't notice. Let me check what I was thinking...

Comment (oising) [reply test/OrleansTestKit.Tests/Tests/TimerTests.cs:11]: Good catch -- I think I wrote that test before writing the cancellation bits, then added another test without thinking. I deleted the first one.

**Review by seniorquico — APPROVED** [review]
